- README.md
- xiaomusic/config.py
> Use MI_HARDWARE in env.

- README.md
> 为支持的设备增加产品名称和官方产品百科链接

- xiaomusic/httpserver.py
- xiaomusic/static/app.js
- xiaomusic/static/index.html
- xiaomusic/xiaomusic.py
reinit时关闭log的handler以修复Windows下保存配置失败的问题。
另外搞了个播放进度😂
> Play process

- xiaomusic/xiaomusic.py
> fix:优化audio_id查询方式

- xiaomusic/config.py
- xiaomusic/static/setting.html
- xiaomusic/xiaomusic.py
初步实现了，不过因为小爱回应语音指令时会自动把歌曲暂停再恢复播放，所有会导致提前播放下一首。后面再看怎么解决吧。
#170
> feat:支持继续播放

- xiaomusic/xiaomusic.py
> hostname can take protocol

- xiaomusic/utils.py
部分 flac 文件好像包括封面，转码之后无法播放，使用 -vn 可以禁止输出 video
> ffmpeg only output audio

- pyproject.toml
- xiaomusic/utils.py
#189 
需要增加一个 python 包，我只修改了 pyproject.toml，pdm.lock 这个文件没改
> 使用 opencc 将歌曲名转化为简体

- xiaomusic/xiaomusic.py
> use threading for building tags

- README.md
- config-example.json
- xiaomusic/config.py
- xiaomusic/static/default/setting.html
- xiaomusic/xiaomusic.py
关联 #112
L05C 通过配置 5-3 可以使用 tts，默认不配置还是 MiNA
> support MiIOService tts

- .github/workflows/fmt.yaml
> format action

- xiaomusic/xiaomusic.py
daeb0ae 写 bug 了，会报错
这个函数得改成 async，不然好像没法阻塞
> bugfix: cannot can async.run when there is a running loop

- xiaomusic/httpserver.py
> bug: fix redirect

- xiaomusic/static/default/app.js
- xiaomusic/static/default/index.html
效果见 #226
代码的写法和之前好像不太一样，看有没有必要对齐？
> refactor: 优化默认UI的搜索框

- xiaomusic/static/default/app.js
- xiaomusic/static/default/index.html
> feat: 默认UI搜索框动态显示

- xiaomusic/httpserver.py
没什么影响的话建议加下这个，这样通过这个接口拿到的信息更完善一些
> feat: 播放状态接口返回当前播放列表

- xiaomusic/httpserver.py
/docs 以及 /static/xxx 可以在未鉴权的情况下访问，添加 basic auth 鉴权
> bug: static和doc添加basic auth

- xiaomusic/static/default/app.js
> refactor: 修改默认UI播放提示词

- xiaomusic/utils.py
> bug: sort results from keyword search

- xiaomusic/httpserver.py
- xiaomusic/xiaomusic.py
> fix: bug in del_music

- xiaomusic/static/index.html
> fix: 小程序码移动端布局兼容

- xiaomusic/config.py
- xiaomusic/static/default/setting.html
- xiaomusic/static/default_past/setting.html
- xiaomusic/utils.py
- xiaomusic/xiaomusic.py
可选下载和转换mp3时，是否均衡的歌曲响度，避免歌声忽大忽小。#336
> feat: 增加均衡歌曲响度（可选）

- Dockerfile
- Dockerfile.builder
- Dockerfile.runtime
Reduce the docker image size by 50%
> Migrate debian to alpine linux
