xiaomusic/static/app.js, xiaomusic/static/index.html, xiaomusic/xiaomusic.py
b站搜索时候,默认搜索到的歌曲可能是别人翻唱的视频,原打算看看能否用yt-dlp或其他工具实现搜索结果预览及选择,在选择后再下载.
目前使用方式:在B站搜索到结果后,根据标题,在面板中填入较为精确的搜索词和文件名,然后再搜索下载,并保存为指定的文件名.例如,搜索"七里香"可能下载到的不是周杰伦的原版,需要根据b站的搜索词排名规则填写才能找到正确版本,可能是"博主abc MV版高清 周杰伦 七里香"这样的搜索词才能定位到想要的,但是下载后又不想把文件名称保存这么长,所以又提供了文件名的input;
=> 将搜索词分为搜索词及文件名两部分,便于更精确搜索以及实现保存下载保存文件名的自定义

xiaomusic/config.py, xiaomusic/xiaomusic.py
1. 语音控制的情况下，部分指令可能干扰小爱原有功能，比如正在播放小爱的歌单，语音控制下一首，会触发到xiaomusic，导致不能正常播歌单的下一首
调整方式：
增加XIAOMUSIC_ACTIVE_CMD的环境变量配置，比如配置成'play,random_play'，那么在非播放状态下，只有这两个指令可以触发，触发后，xiaomusic进入playing状态，其他指令则可以正常触发。
2. https://github.com/hanxi/xiaomusic/issues/36#issue-2258831068 
调整方式：
语音指令解析为空的情况下，如果当前是playing状态，那么执行stop
以上调整不影响控制面板操作的情况
=> 可配置xiaomuisc激活指令,其他指令需要激活后才能使用

xiaomusic/xiaomusic.py
由于Windows路径中使用反斜杠（\）作为目录分隔符，而在URL编码中反斜杠被视为特殊字符所导致windows下拼接得到的url不符合预期 示例
filename：music\outside.mp3
预期：
url: /music/outside.mp3
实际：
url：/music%5Coutside.mp3
需要一个办法来处理windows下的\\路径分隔符,我给出了一种简单的解法,作者可以考虑看看怎么处理会完全一点
=> 修复windows下路径分隔符被视为转移符导致音箱无法播放音乐的问题

xiaomusic/cli.py, xiaomusic/utils.py, xiaomusic/xiaomusic.py
1. Windows在pycharm下运行时会因为读取配置文件的编码问题无法正确加载配置文件
解决：手动指定编码为utf-8
2. m4a格式的文件通过mutagen无法获取到播放时长导致一直单曲循环
解决：改为通过ffprobe获取音频时长。
docker下minetypes获取不到m4a的类型，所以改用文件名判断是否为m4a
不是很擅长python，如有问题请见谅。
=> 修复m4a格式获取时长，指定读取文件的编码格式

xiaomusic/utils.py, xiaomusic/xiaomusic.py
如题
1. 本地搜索可以返回多个匹配（list）
2. 本地搜索不为空的话，更新结果为“当前”播放列表，后续只播放“当前”列表中的歌曲
3. 搜索在模糊匹配前，增加了一个关键词检测（自测原来的包对不太支持关键词检测，0.6匹配不到，0.1匹配太宽松）
对于 `_play` 函数:
`exact`: 精确匹配，用在下一首/上一首/播放列表
`update_cur`: 只有通过 `play` 调用才更新“当前”列表
=> 搜索多个结果，并更新“当前”播放列表

xiaomusic/utils.py, xiaomusic/xiaomusic.py
根据 [c72a619](https://github.com/hanxi/xiaomusic/commit/c72a619df0063a5a87994cee6ff40ff6ee8a000e)，将搜索歌曲得到的播放列表存下来以在前端显示，改名为“临时搜索列表”。
对于 #186 
1. 文件名包括文件夹路径：取完整路径作为music name（由于 name 变长了，原来模糊匹配的相似度可能会降低）
2. 播放列表排序：后端改成了有序字典并调整了 music_list 的构建顺序（前端好像不能区分列表种类，我也不太会这种特殊规则的前端排序实现）
=> 搜索的歌曲存成列表供前端显示；实现额外索引

xiaomusic/utils.py
搜索中已经匹配的项目应该在后续搜索中排出，避免出现重复结果。
=> hotfix: multi-stage search may result in duplicates

xiaomusic/httpserver.py
Fixes [https://github.com/hanxi/xiaomusic/security/code-scanning/32](https://github.com/hanxi/xiaomusic/security/code-scanning/32)
To fix the problem, we should replace the MD5 hashing algorithm with a stronger and more secure algorithm. For general cryptographic purposes, SHA-256 is a good choice. We will use the `hashlib.sha256` function to replace the `hashlib.md5` function.
- Replace the `hashlib.md5` call with `hashlib.sha256`.
- Ensure that the rest of the code remains unchanged to maintain existing functionality.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 32: Use of a broken or weak cryptographic hashing algorithm on sensitive data

xiaomusic/xiaomusic.py
Fixes [https://github.com/hanxi/xiaomusic/security/code-scanning/33](https://github.com/hanxi/xiaomusic/security/code-scanning/33)
To fix the problem, we need to replace the MD5 hashing algorithm with a stronger and more secure cryptographic hash function. In this case, SHA-256 is a suitable choice as it is widely used and considered secure for general cryptographic purposes.
- Replace the `hashlib.md5` function with `hashlib.sha256`.
- Ensure that the rest of the code remains unchanged to maintain existing functionality.
- Update the import statements if necessary to include any new dependencies.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 33: Use of a broken or weak cryptographic hashing algorithm on sensitive data

xiaomusic/httpserver.py
=> request.url.path 无法正确解析路径中特殊字符

xiaomusic/xiaomusic.py
模糊匹配范围太大会导致默认 UI 的播放歌曲不可用（文件名相似时，无法精确选择某一首歌）
限制如果存在精确匹配，就只返回一个结果。
=> bug: 可以精确匹配结果时不采用模糊搜索策略

xiaomusic/utils.py
当前的 `chinese_to_number` 函数在处理某些中文数字（如"十、十一"）时存在问题。
- 添加了对以"十"开头的数字的特殊处理
- 优化了数字转换逻辑
- "十" => 10
- "十一" => 11
- "二十" => 20
- "二十一" => 21
所有测试用例均通过。
=> fix: 修复中文数字转换函数对'十、十一'等数字的处理

xiaomusic/static/default/setting.html, xiaomusic/static/default/setting.js, xiaomusic/static/default/style.css
=> feat: 未发现小爱设备时给予提示

xiaomusic/static/default/app.js
#286 修复安卓低版本webview对audio的src为空值时的报错问题
=> fix: 安卓低版本webview对audio的src为空值的报错

xiaomusic/utils.py
Fixes [https://github.com/hanxi/xiaomusic/security/code-scanning/38](https://github.com/hanxi/xiaomusic/security/code-scanning/38)
To fix the problem, we need to ensure that the constructed file path is safe and does not allow directory traversal or other unintended file access. We can achieve this by normalizing the path and ensuring it is contained within a safe root directory.
1. Normalize the constructed file path using `os.path.normpath`.
2. Ensure the normalized path starts with the intended root directory (`/app`).
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 38: Uncontrolled data used in path expression

xiaomusic/static/tailwind/main.css
修复 tailwind主题 手机端播放列表 歌曲名称超长溢出问题。
因为不是很清楚具体主题样式实现的原理，直接在main.css中添加了修复代码，如果不合适请回复一下，谢谢。
修复前存在的问题：
修复后的效果：
=> 修复tailwind主题样式问题

xiaomusic/xiaomusic.py
现象为未开启模糊匹配提示播放错误，看日志是无法找到对应的歌曲。定位到这里的返回值应该是一个数组，故修改
=> fix: 未开启模糊匹配播放错误问题

xiaomusic/utils.py
_get_web_music_duration函数中缺失await导致时长无法计算
=> fix：get_web_music_duration await缺失导致的时长计算错误bug

xiaomusic/utils.py
Potential fix for [https://github.com/hanxi/xiaomusic/security/code-scanning/47](https://github.com/hanxi/xiaomusic/security/code-scanning/47)
To fix the issue, the code should parse the URL using `urlparse` and check the `hostname` field instead of performing a substring check. This ensures that the check is performed on the actual host of the URL, avoiding false positives caused by substrings appearing elsewhere in the URL.
**Steps to fix:**
1. Replace the substring check `"space.bilibili.com" in url` with a check on the parsed hostname using `urlparse(url).hostname`.
2. Ensure that the hostname matches `space.bilibili.com` exactly or ends with `.space.bilibili.com` to allow for subdomains if necessary.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 47: Incomplete URL substring sanitization

xiaomusic/xiaomusic.py
只处理文件创建、删除和移动事件，避免处理不必要的事件类型。降低动作触发概率，避免过度刷新，产生不必要的bug。
语音控制下的丢失name，bug，暂无头绪。
=> fix: 文件监控忽略非文件增删移动事件的触发
